### ISSUE TITLE
License product name mismatch

### ISSUE THREAD

**Issue by fen-x** [vhbit/swift-linter#1]
There are a couple of places I have found clang format mentions:
- [LICENSE](https://github.com/vhbit/swift-linter/blob/master/LICENSE#L14)
- [SwiftLintLinter.php](https://github.com/vhbit/swift-linter/blob/master/lint/linter/SwiftLintLinter.php#L4)

Could you please fix at least license file, to allow me to use your code in my project.

**Comment by vhbit** [comment]
@fen-x thanks for reporting

**Comment by fen-x** [comment]
Thank you. That helps me a lot.

**Comment by vhbit** [comment]
I just wonder will you use this linter as a part of your build pipeline or you plan to build something new on top of it?

**Comment by fen-x** [comment]
As a part of build pipeline. Just want to be on the safe side from legal perspective.
